services:
  chrome:
    image: selenium/standalone-chrome:4.11.0-20230801
    shm_size: 2g
    networks:
      - test-network

  gateway-proxy:
    build: ./gateway-proxy
    networks:
      - test-network
    ports:
      - "9000:80"
    volumes:
      - ./gateway-proxy:/app

  test-runner:
    build: ./test-runner
    depends_on:
      - gateway-proxy
    networks:
      - test-network
    stdin_open: true
    tty: true
    volumes:
      - ./test-runner:/app

networks:
  test-network:
    driver: bridge